FROM zefhemel/silverbullet:v2

# Set some environment variables
ENV SB_INDEX_PAGE=SilverBullet
ENV SB_READ_ONLY=1

# Add the website content
ADD website /space

# Add excalidraw plug
ADD https://github.com/LogeshG5/silverbullet-excalidraw/releases/download/edge/excalidraw.plug.js /space/
ADD https://github.com/MrMugame/silversearch/releases/download/edge/silversearch.plug.js /space/
