ARG BASE_IMAGE=zefhemel/silverbullet:v2
FROM ${BASE_IMAGE}

# Set some environment variables
ENV SB_INDEX_PAGE=SilverBullet
ENV SB_READ_ONLY=1

# Add the website content
ADD website /space

# Add silversearch plug
ADD https://github.com/MrMugame/silversearch/releases/download/edge/silversearch.plug.js /space/
