// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Template = 1,
  TemplateElement = 2,
  Text = 3,
  ExpressionDirective = 4,
  ExpressionDirectiveOpenTag = 5,
  BlockDirectiveContent = 6,
  DirectiveTagEnd = 7,
  BlockDirective = 8,
  BlockDirectiveOpenTagStart = 9,
  BlockName = 10,
  BlockDirectiveCloseTagStart = 11
