// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Expression = 2,
  Value = 3,
  Number = 4,
  String = 5,
  Bool = 6,
  BooleanKW = 7,
  Regex = 8,
  Identifier = 9,
  List = 11,
  LVal = 12,
  Attribute = 13,
  ParenthesizedExpression = 14,
  LogicalExpression = 15,
  BinExpression = 18,
  InKW = 19,
  Call = 20
