name: configuration-manager
assets:
  - "assets/**"
functions:
  openConfiguration:
    path: ./configuration.ts:openConfiguration
    command:
      name: "Configuration: Open"
      key: "Ctrl-,"
      mac: "Cmd-,"
      requireMode: rw
  saveConfiguration:
    path: ./configuration.ts:saveConfiguration
