use std::path::Path;

/// Resolved configuration for launching the headless browser.
#[derive(Debug, Clone)]
pub struct ChromeConfig {
    pub chrome_path: String,
    pub server_url: String,
    /// Headless auth token, always appended to the page URL as `&token=…`. When
    /// authentication is disabled the open server ignores it; when enabled, the
    /// headless-token authorizer accepts it so the headless page is authorized.
    pub headless_token: String,
    pub user_data_dir: String,
    pub show: bool,
    /// Forward the headless page's captured `console.*` output to the server's
    /// `tracing` log (under the `runtime_console` target) in addition to the
    /// `/.runtime/logs` buffer. On by default; disabled with
    /// `SB_CHROME_LOG_CONSOLE=0`.
    pub log_console: bool,
}

impl ChromeConfig {
    /// Build from the process environment. `server_url` is the loopback base
    /// URL the headless page should load (`http://127.0.0.1:<port><prefix>`);
    /// `headless_token` is always generated by the caller; it's only consulted
    /// by the auth layer when authentication is enabled.
    pub fn from_env(
        server_url: String,
        headless_token: String,
        space_folder: &str,
        read_only: bool,
    ) -> Option<Self> {
        let env = |k: &str| std::env::var(k).ok().filter(|v| !v.is_empty());
        let runtime_api_enabled =
            !matches!(env("SB_RUNTIME_API").as_deref(), Some("0") | Some("false"));
        Self::resolve(
            env("SB_CHROME_PATH"),
            env("CHROMIUM_PATH"),
            server_url,
            headless_token,
            space_folder.to_string(),
            env("SB_CHROME_SHOW").is_some(),
            // On by default; disabled only with SB_CHROME_LOG_CONSOLE=0/false
            // (matches the SB_RUNTIME_API opt-out convention).
            !matches!(
                env("SB_CHROME_LOG_CONSOLE").as_deref(),
                Some("0") | Some("false")
            ),
            read_only,
            runtime_api_enabled,
        )
    }

    /// Pure resolution (unit-tested). Returns `None` when the runtime API is
    /// disabled, the space is read-only, or no Chrome can be found.
    #[allow(clippy::too_many_arguments)]
    pub fn resolve(
        sb_chrome_path: Option<String>,
        chromium_path: Option<String>,
        server_url: String,
        headless_token: String,
        space_folder: String,
        show: bool,
        log_console: bool,
        read_only: bool,
        runtime_api_enabled: bool,
    ) -> Option<Self> {
        if !runtime_api_enabled || read_only {
            return None;
        }
        let chrome_path = sb_chrome_path.or(chromium_path).or_else(find_chrome)?;
        let user_data_dir = std::env::var("SB_CHROME_DATA_DIR")
            .ok()
            .filter(|v| !v.is_empty())
            .unwrap_or_else(|| {
                Path::new(&space_folder)
                    .join(".chrome-data")
                    .to_string_lossy()
                    .into_owned()
            });
        Some(Self {
            chrome_path,
            server_url,
            headless_token,
            user_data_dir,
            show,
            log_console,
        })
    }
}

/// Find a Chrome/Chromium executable from platform-specific candidates.
pub fn find_chrome() -> Option<String> {
    if cfg!(target_os = "macos") {
        let candidates: &[&str] = &[
            "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
            "/Applications/Chromium.app/Contents/MacOS/Chromium",
        ];
        return resolve_candidates(candidates);
    }

    if cfg!(target_os = "windows") {
        let mut candidates: Vec<String> = vec![
            "chrome".to_string(),
            "chrome.exe".to_string(),
            r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe".to_string(),
            r"C:\Program Files\Google\Chrome\Application\chrome.exe".to_string(),
        ];
        if let Some(profile) = std::env::var_os("USERPROFILE") {
            let profile = Path::new(&profile);
            candidates.push(
                profile
                    .join(r"AppData\Local\Google\Chrome\Application\chrome.exe")
                    .to_string_lossy()
                    .into_owned(),
            );
            candidates.push(
                profile
                    .join(r"AppData\Local\Chromium\Application\chrome.exe")
                    .to_string_lossy()
                    .into_owned(),
            );
        }
        let refs: Vec<&str> = candidates.iter().map(String::as_str).collect();
        return resolve_candidates(&refs);
    }

    let candidates: &[&str] = &[
        "headless_shell",
        "headless-shell",
        "chromium",
        "chromium-browser",
        "google-chrome",
        "google-chrome-stable",
        "/usr/bin/google-chrome",
        "/snap/bin/chromium",
    ];
    resolve_candidates(candidates)
}

/// Resolve the first candidate that exists: absolute paths are checked
/// directly, bare names are looked up on `PATH`.
fn resolve_candidates(candidates: &[&str]) -> Option<String> {
    for c in candidates {
        if Path::new(c).is_absolute() {
            if Path::new(c).exists() {
                return Some((*c).to_string());
            }
        } else if let Some(found) = which_on_path(c) {
            return Some(found);
        }
    }
    None
}

fn which_on_path(name: &str) -> Option<String> {
    let path = std::env::var_os("PATH")?;
    for dir in std::env::split_paths(&path) {
        let full = dir.join(name);
        if full.is_file() {
            return Some(full.to_string_lossy().into_owned());
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn explicit_path_wins_over_discovery() {
        let cfg = ChromeConfig::resolve(
            Some("/custom/chrome".into()),
            None,
            "http://127.0.0.1:3000".into(),
            String::new(),
            "/tmp/space".into(),
            false,
            false,
            false,
            true,
        );
        assert_eq!(cfg.unwrap().chrome_path, "/custom/chrome");
    }

    #[test]
    fn chromium_path_is_fallback_for_explicit() {
        let cfg = ChromeConfig::resolve(
            None,
            Some("/usr/bin/chromium".into()),
            "u".into(),
            String::new(),
            "/s".into(),
            false,
            false,
            false,
            true,
        );
        assert_eq!(cfg.unwrap().chrome_path, "/usr/bin/chromium");
    }

    #[test]
    fn disabled_when_runtime_api_off_or_read_only() {
        assert!(ChromeConfig::resolve(
            Some("/x".into()),
            None,
            "u".into(),
            String::new(),
            "/s".into(),
            false,
            false,
            false,
            false
        )
        .is_none());
        assert!(ChromeConfig::resolve(
            Some("/x".into()),
            None,
            "u".into(),
            String::new(),
            "/s".into(),
            false,
            false,
            true,
            true
        )
        .is_none());
    }

    #[test]
    fn data_dir_defaults_under_space() {
        let cfg = ChromeConfig::resolve(
            Some("/x".into()),
            None,
            "u".into(),
            String::new(),
            "/space".into(),
            false,
            false,
            false,
            true,
        )
        .unwrap();
        assert!(cfg.user_data_dir.ends_with(".chrome-data"));
        assert!(cfg.user_data_dir.contains("space"));
    }

    #[test]
    fn token_show_and_log_console_flow_through() {
        let cfg = ChromeConfig::resolve(
            Some("/x".into()),
            None,
            "u".into(),
            "tok123".into(),
            "/s".into(),
            true,
            true,
            false,
            true,
        )
        .unwrap();
        assert_eq!(cfg.headless_token, "tok123");
        assert!(cfg.show);
        assert!(cfg.log_console);
    }
}
