// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Query = 2,
  Name = 3,
  WhereClause = 4,
  LogicalExpr = 5,
  AndExpr = 6,
  FilterExpr = 7,
  Value = 8,
  Number = 9,
  String = 10,
  Bool = 11,
  Regex = 12,
  Null = 13,
  OrderClause = 14,
  Order = 15,
  LimitClause = 16
