name: Server

on:
  push:
    tags:
      - "*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.6.8
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25.1"
      - name: Compile client and plug-compile with Deno
        run: |
          deno task build-production
          deno task build-plug-compile
      - name: Build Go binaries for multiple platforms
        run: make build-server-releases
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: |
            dist/plug-compile.js
            silverbullet-*.zip
